# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spXqlmAQs49uL-aZSXanK5r6YtpKLmIw
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# Avoid streaming caching issues on some platforms:
st.set_page_config(page_title="Dubai Real Estate Price Predictor", page_icon="🏙️", layout="wide")

# Sidebar with info
st.sidebar.image("https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80", use_column_width=True)
st.sidebar.header("Dubai Property Insights")
st.sidebar.markdown("""
**By Pratham Krunal Lineswala**

Upload your CSV file or use one with latest 10,000 rows sample for fast loading.
""")

# Main title and subtitle
st.markdown("""
<h1 style='text-align: center; color: #145DA0;'>🏠 Dubai Real Estate Price Predictor</h1>
<p style='text-align: center; color: #222831;'>Enter property features and instantly estimate the price with ML!</p>
<hr>
""", unsafe_allow_html=True)

# Load and clean data
@st.cache_data
def load_data(file, n=10000):
    df = pd.read_csv(file, nrows=n)

    def clean_price(price):
        try:
            price = str(price).replace(',', '').replace('AED', '').strip()
            return float(re.sub(r'[^0-9.]', '', price))
        except:
            return np.nan

    df['price'] = df['price'].apply(clean_price)
    df = df.dropna(subset=['price'])
    df = df[df['type'] == 'Residential for Sale']

    df['size_sqft'] = df['sizeMin'].str.extract(r'(\d+)').astype(float)

    for col in ['bathrooms', 'bedrooms', 'size_sqft']:
        df[col] = df[col].astype(str).str.extract(r'(\d+)')
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col].fillna(df[col].median(), inplace=True)

    df['furnishing'] = df['furnishing'].fillna('No').str.capitalize()
    return df

# Model training function
@st.cache_resource
def train_model(df):
    features = ['bathrooms', 'bedrooms', 'size_sqft', 'furnishing']
    X = df[features]
    y = df['price']

    pipeline = Pipeline([
        ('preprocess', ColumnTransformer([
            ('num', Pipeline([
                ('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())
            ]), ['bathrooms', 'bedrooms', 'size_sqft']),
            ('cat', Pipeline([
                ('imputer', SimpleImputer(strategy='most_frequent')),
                ('ohe', OneHotEncoder(handle_unknown='ignore'))
            ]), ['furnishing'])
        ])),
        ('model', RandomForestRegressor(n_estimators=50, random_state=42))
    ])

    pipeline.fit(X, y)
    return pipeline


# File uploader widget
uploaded_file = st.file_uploader("Upload your real estate CSV dataset", type=['csv'])

if uploaded_file:
    with st.spinner('Loading and processing dataset...'):
        data = load_data(uploaded_file)
        model = train_model(data)
    st.success("Dataset loaded and model trained successfully! Enter your property details below:")
else:
    st.warning("Please upload the dataset CSV file to proceed.")
    st.stop()

# User input interface
left, mid, right = st.columns([1, 2, 1])

with mid:
    st.subheader("Property Details")

    bathrooms = st.slider("Bathrooms", 0, 10, 2)
    bedrooms = st.slider("Bedrooms", 0, 10, 2)
    size_sqft = st.number_input("Property Size (sqft)", 200, 20000, 1000, 10)
    furnishing = st.radio("Furnishing", ["Yes", "No"], horizontal=True)

    input_df = pd.DataFrame({
        'bathrooms': [bathrooms],
        'bedrooms': [bedrooms],
        'size_sqft': [size_sqft],
        'furnishing': [furnishing]
    })

    if st.button("🎬 Predict Price!"):
        prediction = model.predict(input_df)[0]
        st.markdown(f"""
        <div style='padding: 16px; background: #F0F5F9; border-radius: 12px; text-align: center; margin-top: 20px;'>
            <h2 style='color: #145DA0;'>💰 Estimated Price: AED {prediction:,.2f}</h2>
        </div>
        """, unsafe_allow_html=True)

# Dataset price distribution plot in expander
with st.expander("📊 Price Distribution (Sample)"):
    import seaborn as sns
    fig, ax = plt.subplots(figsize=(9, 3))
    sns.histplot(data['price'], bins=40, color="#145DA0", ax=ax)
    ax.set_xlabel("Price (AED)")
    ax.set_ylabel("Count")
    ax.set_title("Sample Price Distribution")
    st.pyplot(fig)

# Footer
st.markdown("""
---
<div style='text-align:center; color:grey; font-size:14px; margin-top:20px;'>
Made with ❤️ in Dubai | Powered by Streamlit
</div>
""", unsafe_allow_html=True)